#!/usr/bin/env bash
# This Script installs Nginx on a linux server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
string="server_name trentness.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default
sudo service nginx restart
