#!/usr/bin/env bash
# configures domain zone

print_info() {
	record_ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4,$5}')
	record=$(echo $record_ip | awk '{print $1}')
	ip=$(echo $record_ip | awk '{print $2}')
	echo "The subdomain $2 is a $record record and points to $ip"
}

if [ $# -eq 1 ]
then
	print_info $1 www
	print_info $1 lb-01
	print_info $1 web-01
	print_info $1 web-02
elif [ $# -eq 2 ]
then
	print_info $1 $2
fi