#!/usr/bin/env bash
# configures domain zone
function parse {
        dest=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -1 | rev | awk -F"\t" '{ print $1 }' | rev)
	rec=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -1 | rev | awk -F"\t" '{ print $2 }' | rev)
}

if [[ -z "$2" ]]
then
        parse www "$1"
	echo "The subdomain www is a $rec record and points to $dest"
	parse lb-01 "$1"
	echo "The subdomain lb-01 is a $rec record and points to $dest"
	parse web-01 "$1"
	echo "The subdomain web-01 is a $rec record and points to $dest"
	parse web-02 "$1"
	echo "The subdomain web-02 is a $rec record and points to $dest"
else
        parse "$2" "$1"
        echo "The subdomain $2 is a $rec record and points to $dest"
fi
