#!/usr/bin/env bash
#script that displays to infinity and beyond indefinitely with a sleep 2 after each in between each iteration of the loop
trap "echo I am invincible!!!" SIGTERM
while true;
do
	echo "To infinity and beyond"
	          sleep 2
done
