#!/usr/bin/env bash
#this script displays Holberton School 10 times with exceptions on the 4th and 8th lines stating bad luck and good luck respectively using while loop and if,elif and else statements

a=1
while [ $a -le 10 ]
do
if [ $a == 4 ]
then
echo "bad luck"
elif [ $a == 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
((a++))
done
